### ISSUE TITLE
Background Script Errors on Reload

### ISSUE THREAD

**Issue by melban** [KangoExtensions/kango#1]
I get the following two errors when reloading my extension in developer mode.  If I add some code to kango/browsers.js the issue goes away but i'm guessing it is something to do with my version being a beta.  This might just be a heads up for a future version of Chrome.  If I'm viewing the console of my background page I get these two errors.  If I refresh the background page by simply hitting F5 things work fine.

Working Version: Chrome 20.0.1132.47 m
Non Working Version: Chrome 21.0.1180.41 beta-m

Uncaught TypeError: Cannot read property 'onActiveChanged' of undefined browser.js:22
   kango.Browser browser.js:22
   (anonymous function) browser.js:25

Uncaught TypeError: Cannot call method 'getURL' of undefined io.js:10
   kango.IO.kango.oop.extend.getExtensionFileContents io.js:10
   kango.oop.mixin._loadExtensionInfo kango.js:16
   kango.oop.mixin._init kango.js:16
   (anonymous function)

This fixes the issue.

kango.Browser=function(){
if( !chrome.tabs )
{
    document.location.reload();
    return;
}

**Comment by akrylysov** [comment]
Seems all is ok with the latest dev Chrome, if not, you shoud create bug report at https://code.google.com/p/chromium/issues/ because it's Chrome issue.
