### ISSUE TITLE
IE library conflicts?

### ISSUE THREAD

**Issue by itonics-tbeauvais** [KangoExtensions/kango#107]
We are seeing a problem in IE11 where the runtime of the plugin and the web page seem to be shared.  We are getting conflicts with the jQuery/jQuery UI libraries loaded on the web page.  This means that some webpages will throw errors!  

When we disable the plugin, the page works fine.

Do you have an insight or experience with such problems?

**Comment by akrylysov** [comment]
You should use `noConflict` to prevent conflicts. Take a look at https://github.com/KangoExtensions/kango-samples/blob/master/ChristmasTree/src/common/tree.js

**Comment by itonics-tbeauvais** [comment]
Thanks for the update, I'll give a shout to our dev and have him take a look.

I might even have him jump in here.

**Comment by nexspy** [comment]
the code works now after adding this line in the background script file.
thankx

var $ = window.$.noConflict(true); // Required for IE
