### ISSUE TITLE
KangoAPI.onReady() not called in IE11

### ISSUE THREAD

**Issue by itonics-tbeauvais** [KangoExtensions/kango#108]
This is a strange, frustrating and un-reproducible error but KangoAPI.onReady() is not getting called in a colleague's instance of Windows 8/IE11.

I have tried reproducing in the ModernIE virtual machines for Win7/8 IE10/11 and can't reproduce. 

If I can provide any other details I will.  Please let me know what you need.  Thanks in advance for any insight.

![c users felix desktop ie11](https://cloud.githubusercontent.com/assets/9199882/5507161/255b5d04-87a1-11e4-953b-edd980e8f90a.png)

**Comment by akrylysov** [comment]
- Do you have any other addons installed? Try to disable them.
- Try to reset IE settings (Settings -> Internet Options -> Advanced -> Reset).

**Comment by itonics-tbeauvais** [comment]
Disabled all other plugins and Reset, no change.

**Comment by itonics-tbeauvais** [comment]
What is the best way to log or debug in IE?

**Comment by akrylysov** [comment]
You can enable Kango debug console. Add `"debug": true` to extension_info.json.

**Comment by akrylysov** [comment]
Did you resolve the issue? or found a way how to reproduce it?

**Comment by duncanmhor** [comment]
We are experiencing the same issue. Is it possible that this is related to https://support.microsoft.com/kb/3008923

**Comment by akrylysov** [comment]
We managed to reproduce the issue and we are trying to find a solution.

**Comment by akrylysov** [comment]
Please try new version 1.7.4. You can download it from your dashboard.
