### ISSUE TITLE
Ошибки в файрфокс 15+

### ISSUE THREAD

**Issue by propostaff** [KangoExtensions/kango#11]
При написании расширения в файрфоксе вылазила ошибка:

Error: Exposing chrome JS objects to content without **exposedProps** is insecure and deprecated. See https://developer.mozilla.org/en/XPConnect_wrappers for more information.

Покопался, такая-же ошибка и при стандартом расширении MessagingDemo

Скриншот: http://s1.hostingkartinok.com/uploads/images/2012/09/7b3d5743ce3daa2a44dff8669d07bef8.jpg

Информация от разработчиков мазиллы: http://blog.mozilla.org/addons/2012/08/20/exposing-objects-to-content-safely/

**Comment by akrylysov** [comment]
Fixed in 0.9.9.

**Comment by braco** [comment]
@kadot: where is 0.9.9? Is there any chance you'll host the code in Github to make updates easier in the future?
