### ISSUE TITLE
addons.mozilla.org validation issues.

### ISSUE THREAD

**Issue by shijuraj** [KangoExtensions/kango#111]
In build provided at http://kangoextensions.com/kango.html with the link http://kangoextensions.com/kango/kango-framework-latest.zip is mentioned as 1.7.1, but it is actually 1.7.3 dev release. 
So mozilla team rejects addon developed in this version, and suggested to use only relese version. So please update the download link with release version.

'settings.py' states:

VERSION = '1.7.3'
BUILD = '36447b11bac0'
PACKAGE_ID = 'dev'

**Comment by akrylysov** [comment]
Duplicate to #122.
