### ISSUE TITLE
Is Kango abandoned and obsolete now?

### ISSUE THREAD

**Issue by Elite** [KangoExtensions/kango#113]
Kango framework will become broken with Firefox 36, I am facing the error `Error: Exposing privileged or cross-origin callable is prohibited` with Kango framework in developer build of Firefox 36. The error is thrown for `kango.invokeasync` method in my content-script.

Is there a way out or not, pls. guide us - don't want to wake up one day with Firefox 36 Final getting pushed to all users putting an end to our extensions?

**Comment by akrylysov** [comment]
What is your Kango version?

**Comment by Elite** [comment]
Version 1.3.0

**Comment by akrylysov** [comment]
This version is one year old - it doesn't support Firefox 36, you should use the latest Kango version.

**Comment by Elite** [comment]
OK, got it. I was signed up for blog updates but never received any information about it.

```
Version 1.7.1
-------------
- Firefox 34+ compatibility
- addons.mozilla.org store compatibility fixes
```
