### ISSUE TITLE
FireFox 36

### ISSUE THREAD

**Issue by davemodis** [KangoExtensions/kango#116]
With update of Firefox 36 extension has been stopped.
Recompiling doesn't helps.

**Comment by akrylysov** [comment]
What is your Kango version?

**Comment by davemodis** [comment]
1.7.1

среда, 4 марта 2015 г. пользователь Artem Krylysov написал:

**Comment by akrylysov** [comment]
Please try to install the latest Kango version http://kangoextensions.com/kango/kango-framework-latest.zip.

**Comment by davemodis** [comment]
Вы говорите по-русски?

После компиляции и установки расширения, иконка просто не появляется.

2015-03-04 16:07 GMT+03:00 Artem Krylysov notifications@github.com:

**Comment by akrylysov** [comment]
> Вы говорите по-русски?

Да, но язык багтрекера - английский.

Прошу выслать скомпилированное расширение на extensions@kangoextensions.com

**Comment by davemodis** [comment]
All files have been sent. Waiting for response
