### ISSUE TITLE
With 1.7.x, the background process KangoEngine.exe does not shutdown when IE is closed

### ISSUE THREAD

**Issue by brian-chun-sp** [KangoExtensions/kango#118]
I upgraded from 1.3.7 to 1.7.4, and I notice that the background process KangoEngine.exe does not shut down when IE is closed. I verified it on IE11 and IE10 with kango 1.71, 1.74 and 1.76. 

It causes issue for browser extension install/uninstall as the process continue to run until the machine is reboot or manually killed in task manager. 

Is this a known issue?

**Comment by akrylysov** [comment]
Please send us your compiled extension to extensions@kangoextensions.com

**Comment by brian-chun-sp** [comment]
a follow-up email and extension have been set set to extensions@kangoextensions.com. Thanks!

**Comment by akrylysov** [comment]
The issue was fixed, please download the new version from your dashboard.
