### ISSUE TITLE
Firefox 36

### ISSUE THREAD

**Issue by Acacia-Jeff** [KangoExtensions/kango#119]
Hello,

I have done an extension with kango 1.2.4, and it's work fine up to Firefox 35.
With Firefox 36, the extension doesn't work anymore (install well but don't do anything).
I try to update kango to its latest version 1.7.6, but it doesn't change anything.

The extension contains only javascript code (Dom manipulation and window.setInterval) and the only call to kango framework is for kango.xhr.send in order to communicate with localhost.

Do you have an idea of the solution ?

**Comment by akrylysov** [comment]
Please send us compiled extension to extensions@kangoextensions.com.

**Comment by Acacia-Jeff** [comment]
Hello,

Sent as requested, any news ?

**Comment by akrylysov** [comment]
You must extract the new Kango version to a new directory.
