### ISSUE TITLE
Firefox, popup window and scrollbar (Kango 0.9.8)

### ISSUE THREAD

**Issue by juanjbarrionuevo** [KangoExtensions/kango#12]
I have an issue in Firefox browser with the popup window: the vertical scrollbar doesn't appear.
It's an intentional behavior?
It's possible to change that behavior?
In Chrome, Opera and Safari browsers, the scrollbar appears correctly and allow see all the content of the page (popup.html).

**Comment by akrylysov** [comment]
Fixed in v0.9.9.

**Comment by juanjbarrionuevo** [comment]
Do you know the release date of kango 0.9.9?
