### ISSUE TITLE
Unchecked runtime.lastError while running windows.get: No window with id: 662

### ISSUE THREAD

**Issue by Zukeh** [KangoExtensions/kango#121]
Hello,

I see this error in the console (background) with the latest chrome version (42). This error shows up all the time, even with the samples.

**Comment by akrylysov** [comment]
It's a known Chrome API issue https://code.google.com/p/chromium/issues/detail?id=93646
It doesn't affect the extension.

**Comment by Zukeh** [comment]
Thanks
