### ISSUE TITLE
Absent support of 1.7.7 version on addons.mozilla.org

### ISSUE THREAD

**Issue by HarryLyu** [KangoExtensions/kango#122]
Hi!

I tried to submit new version of my extension to AMO with Kango 1.7.7, but got a reject because of

> I'm sorry we currently allow Kango 1.7.0 and 1.7.1 only. Please use either of these versions.

How can I use last version of Kango? Do you plan to contact AMO for supporting last versions?

**Comment by akrylysov** [comment]
We are waiting for review.

**Comment by apatrida** [comment]
No update on the review?

**Comment by akrylysov** [comment]
Kango 1.7.9 was resubmitted to addons.mozilla.

**Comment by craig-forster-sp** [comment]
Any update on this?

**Comment by akrylysov** [comment]
You should use version 1.7.9.

**Comment by nattster** [comment]
@akrylysov  Today, I just submitted extension with Kango 1.7.9 to Preliminary review with Firefox.
I'm still getting:

`1) I'm sorry, we currently allow Kango 1.7.0 and 1.7.1 only. Please use either of these versions.`

Should I try Full Review?

**Comment by EngrAhsanAli** [comment]
Please downgrade to 1.7.9

https://drive.google.com/file/d/0B-j3X0RoYciuY0JYN2pTdnY3cFU/view?usp=sharing
