### ISSUE TITLE
dispatchMessage - doesn't work in firefox

### ISSUE THREAD

**Issue by ghost** [KangoExtensions/kango#125]
I am trying to send notification from content to background script and it work in all browsers exept firefox.

Firefox: 38.0.1
Kango: 1.7.6
Content.js
`kango.dispatchMessage('notification', 'example');`
Main.js
`kango.addMessageListener('notification', function(event) ...`

**Comment by akrylysov** [comment]
Please send us your extension.

**Comment by ghost** [comment]
I have sent you extension with code.

**Comment by akrylysov** [comment]
It works fine, you just shouldn't use `alert` in background scripts because it is not available. We'll add it to documentation.
