### ISSUE TITLE
Mozilla team do not accept Kango framework higher than version 1.7.1.

### ISSUE THREAD

**Issue by VT2** [KangoExtensions/kango#126]
Mozilla team rejects addon developed in version 1.7.6: "we currently do not accept Kango framework higher than version 1.7.1."
Where download Kango framework version 1.7.1?

**Comment by apatrida** [comment]
Why is this rejection happening?

**Comment by VT2** [comment]
Letter from the Mozilla team:
"Your add-on, PersiaHR Extension 1.3.3, has been reviewed by an editor and did not meet the criteria for being hosted in our gallery.
Reviewer: erosman
Comments: Your version was rejected because of the following problems:
1) Unfortunately, we currently do not accept Kango framework higher than version 1.7.1.
Please fix them and submit again. Thank you."

**Comment by iamolivinius** [comment]
Is there any way to download older kango releases?

**Comment by akrylysov** [comment]
@iamolivinius if you purchased commercial license, you can download older releases in your dashboard.

**Comment by akrylysov** [comment]
Kango 1.7.9 was resubmitted to addons.mozilla.

**Comment by akrylysov** [comment]
Duplicate to #122.
