### ISSUE TITLE
Access browser's settings ?

### ISSUE THREAD

**Issue by enguerranws** [KangoExtensions/kango#129]
Hi !

I was wondering if there any way to access browser's setting ? I'm currently trying to make an extension that open an url on new tab / new window, so the simplest way would be to change default browser's homepage.

If it's not possible to access those settings with Kango API, do you see any way to achieve something that wuld have the same behavior using Kango API ?

**Comment by akrylysov** [comment]
There is no way to change browser settings in Kango.
