### ISSUE TITLE
Kango extensions do not work in current Firefox nightly

### ISSUE THREAD

**Issue by iamolivinius** [KangoExtensions/kango#131]
checked out the latest christmas tree sample from the sample repository and build it with kango 1.7.6.

in chrome: a christmas tree appears in every single webpage
in firefox nighty(42.0a): NO christmas tree appears

In FF browser console i can see new messages. "unsafe CPOW usage"

I tested it to against the current nightly. This issue probably appears on earlier versions of FF too.

**Comment by akrylysov** [comment]
Firefox 42 is not currently supported. We are working on it.

**Comment by iamolivinius** [comment]
Great news!

Will this be in time for the official FF release date on Nov. 3rd?
Are u gonna switch internals to add-ons SDK?

**Comment by akrylysov** [comment]
> Will this be in time for the official FF release date on Nov. 3rd?

Sure, we will release new version before new Firefox release.

> Are u gonna switch internals to add-ons SDK?

No, we don't have such plans.

**Comment by iamolivinius** [comment]
Are you planing to support extension signing as an option for the kango cli? Because FF42+ won't run unsigned extensions anymore.

**Comment by akrylysov** [comment]
You shouldn't sign the extension manually, you should upload it to AMO. More details https://wiki.mozilla.org/Addons/Extension_Signing.

**Comment by iamolivinius** [comment]
Sorry, my bad. Stumbled over this link a few seconds ago. Thanks

**Comment by brian-chun-sp** [comment]
FF 41 has just released today. Do we have a solution for supporting FF 42 yet?

**Comment by akrylysov** [comment]
Fixed in 1.8.0.
