### ISSUE TITLE
dispatchMessage not working in IE11 - kango 1.7.9

### ISSUE THREAD

**Issue by dthomp24** [KangoExtensions/kango#137]
The MessagingDemo does not work in IE11 on Windows 7. The dispatchMessage call in main.js produces the console output, "Error in script (unknown): Object doesn't support this property or method".

**Comment by ar7casper** [comment]
@dthomp24 Did you find a solution?
I'm on win8.1 & IE11

**Comment by akrylysov** [comment]
It was fixed in Kango 1.7.10.

**Comment by ar7casper** [comment]
Hello Artem,

Thank you for your reply.
Could you please help me understand what was fixed under -
"IE: Content script engine bug fixes"
under the fixes of 1.7.9?

Thank you in advance,
Alex Raihelgaus.

Alex
