### ISSUE TITLE
ContextMenuIItem not working in IE11

### ISSUE THREAD

**Issue by dthomp24** [KangoExtensions/kango#143]
The ContextMenuItem is not working in IE11 using kango 1.7.9 or 1.7.10. After compiling the [ContextMenuItem sample](https://github.com/KangoExtensions/kango-samples/tree/master/ContextMenuItem) and running it in IE11, the kango.ui.contextMenuItem.event.CLICK handler does not run. There is a console log message in main.js that does not get displayed.

**Comment by akrylysov** [comment]
Was fixed in Kango 1.7.11.
