### ISSUE TITLE
Firefox e10s support in Kango

### ISSUE THREAD

**Issue by olloff** [KangoExtensions/kango#144]
Hi. Firefox enabled its multiprocess environment in Firefox Developer Edition (Aurora build) recently. And Kango, as you must be knowing, doesn't support e10s mode (Firefox Aurora and Firefox Nightly working almost flowless with e10s disabled).

Will Kango support e10s, do you can sound any milestone?

**Comment by akrylysov** [comment]
e10s support is already implemented in Kango, we are fixing minor issues and testing it right now.

**Comment by olloff** [comment]
Nice to hear that, @akrylysov, thank for your answer.

**Comment by olloff** [comment]
@akrylysov I feel, I need to bump this question once again.

Last version of Kango stated on [your page](http://kangoextensions.com/kango.html) is 1.7.9. Does e10s support already implemented in that particular version?

If not, do you have any ideas when you plan to ship e10s version?

**Comment by akrylysov** [comment]
e10s implemented in version 1.8.0 http://kangoextensions.com/blog/2016/01/09/version-180/.

**Comment by olloff** [comment]
Now I feel like you've made it just for me. Many thanks!
