### ISSUE TITLE
Safari icon black?

### ISSUE THREAD

**Issue by dovy** [KangoExtensions/kango#150]
https://cloudup.com/cpy-m9ceEgH

Works fine in Chrome, just Safari.

Safari 9.0.3 on mac.

**Comment by eppfel** [comment]
Yes, this is quite annoying. Safari needs a special png as mask: https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/AddingButtonstotheMainSafariToolbar/AddingButtonstotheMainSafariToolbar.html
I manually replace the icon in the Safari Extension Builder for now. No better solution right now.

**Comment by dovy** [comment]
Wow, I know illustrator and photoshop, but there are like no tutorials on how the crap to do this. hah.

**Comment by dovy** [comment]
Thanks though. I'll find how to do it and report here.

**Comment by akrylysov** [comment]
You can just put Safari specific icon.png to your src/safari/icon directory.
