### ISSUE TITLE
Chrome extension not working

### ISSUE THREAD

**Issue by ierror** [KangoExtensions/kango#158]
I downloaded the latest version and got my first extension running in Firefox and Safari \o/
On Chrome i get this error:

`browser_button.js:11 Uncaught ReferenceError: teio is not defined`

Does anybody know what trio is for? It seems like a typo, there is only one match for:

`grep -R teio ../kango/
../kango//src/js/chrome/kango-ui/browser_button.part.js:function BrowserButton(t){BrowserButtonBase.call(this,t),this._popupDetails=null,chrome.browserAction.onClicked.addListener(func.bind(this._onClicked,this)),this._initDetails(t)}var extensionInfo=require("kango/extension_info"),utils=require("kango/utils"),object=utils.object,func=utils.func,io=require("kango/io");BrowserButton.prototype=object.extend(BrowserButtonBase,{_onClicked:function(){return this.fireEvent(this.event.COMMAND)},_initDetails:function(t){object.isObject(t)&&(object.isString(t.icon)&&this.setIcon(t.icon),object.isString(t.caption)&&this.setCaption(t.caption),object.isString(t.tooltipText)&&this.setTooltipText(t.tooltipText),object.isObject(t.popup)&&this.setPopup(t.popup))},setTooltipText:function(t){chrome.browserAction.setTitle({title:t.toString()})},setCaption:function(t){},setIcon:function(t){chrome.browserAction.setIcon({path:teio.getFileUrl(t)})},setBadgeValue:function(t){chrome.browserAction.setBadgeText({text:null!=t&&0!=t?t.toString():""})},setBadgeBackgroundColor:function(t){chrome.browserAction.setBadgeBackgroundColor({color:t})},setPopup:function(t){this._popupDetails=t;var o="";t&&t.url&&(o=t.url),chrome.browserAction.setPopup({popup:o})},getPopupDetails:function(){return this._popupDetails},setContextMenu:function(){}}),extensionInfo.browser_button&&(module.exports=new BrowserButton(extensionInfo.browser_button),module.exports.getPublicApi=getPublicApi);`

**Comment by akrylysov** [comment]
Where did you get your framework version? Kango doesn't contain any `teio` references. Try to download Kango from http://kangoextensions.com/kango/kango-framework-latest.zip.
