### ISSUE TITLE
kango.console.log - No output string to browser console.

### ISSUE THREAD

**Issue by jupiterit** [KangoExtensions/kango#17]
On firefox v. 15.0.1 an chrome v. 18.0.1025.168 (Build 134367 Linux),both on linux equipped with Ubuntu 10.04

A part of my code in main.js:

kango.ui.browserButton.addEventListener(kango.ui.browserButton.event.Command, function() {
    kango.console.log('ciao1');
    alert('ciao2');
});

alert window is called but any output on browser console

**Comment by akrylysov** [comment]
In Chrome to see console you shoud open Tools -> Extensions, turn on "Developer mode" and click to "background.html" of your extesnion.
In Firefox you should open Tools -> Web Developer -> Error Console.
