### ISSUE TITLE
Banned element in install.rdf

### ISSUE THREAD

**Issue by braco** [KangoExtensions/kango#18]
When uploading the generated xpi to addons.mozilla.org:

```
Banned element in install.rdf
Error: The element "updateURL" was found in the add-on's install.rdf file. It is not allowed in add-ons under the current configuration.
```

when removing update_url from extension_info.json:

```
Error: Command failed: Traceback (most recent call last):
...
ValueError: Expecting property name: line 14 column 3 (char 319)
```

how can we host Kango generated files in the proper update channels?

**Comment by braco** [comment]
This is also a problem in the Chrome Web Store, which requires that line removed and format is changed to .zip.

Maybe Kango should produce chrome-web-store.zip and mozilla-extensions-site.zip for uploading to those third parties?

**Comment by akrylysov** [comment]
Please attach project that produce "ValueError: Expecting property name: line 14 column 3 (char 319)".

> Maybe Kango should produce chrome-web-store.zip and mozilla-extensions-site.zip for uploading to those third parties?

We will think about it, usually developers have addons with update_url_path or without it, not both.

**Comment by melban** [comment]
I've found that Chrome 22 does not allow my extensions to update using the updateURL setting but rather mandates that my extension be listed in the Chrome Webstore.  Since I had an install base I had to add my extension to the webstore with my Extension ID in the manifest.json file so that when I point to the new updateURL in my hosted .crx file all my users would then pick up with the Webstore hosted app.

**Comment by braco** [comment]
@artemkrylysov: the problem is that the stores (chrome & mozilla) require that there are no updateURL directives, but if you remove them, kango won't compile. I guess the build process is now: run Kango, edit archive to remove updateURL, save, upload?

edit: this seems to be fixed with the new version of Kango if the generator is run from scratch.
