### ISSUE TITLE
TypeError: kango.getExtensionInfo is not a function

### ISSUE THREAD

**Issue by melban** [KangoExtensions/kango#19]
Firefox 16.0
Kango: 0.9.8
OS: Windows XP

From a content script I'm trying to run "kango.getExtensionInfo()" and I receive the message "TypeError: kango.getExtensionInfo is not a function".  Sample code below.  I have been calling getExtensionInfo() from a background script on FF 16.0 successfully. 

var stateWatcher = setInterval(function()
{
    if (document.readyState === "complete")
    {
        try{
            PSChromeVersion = kango.getExtensionInfo();
            clearInterval(stateWatcher);
        } catch(e){ kango.console.log( e.toString() ); }
    }
}, 1000);

**Comment by akrylysov** [comment]
> From a content script I'm trying to run "kango.getExtensionInfo()" and I receive the message "TypeError: kango.getExtensionInfo is not a function".

Not a bug, only some APIs available from content scripts. More details at http://kangoextensions.com/docs/general/content-scripts.html.

``` javascript
var stateWatcher = setInterval(function()
{
if (document.readyState === "complete")
{
try{
PSChromeVersion = kango.getExtensionInfo();
clearInterval(stateWatcher);
} catch(e){ kango.console.log( e.toString() ); }
}
}, 1000);
```

You don't need to do that because content scripts runs on DOMContentLoaded event.

**Comment by melban** [comment]
Thank you very much for pointing out my easy mistake.  Thanks again for 
the great tool in building multi-browser extensions.  I look forward to 
the future of KangoExtensions and the possibility to use it for a paying 
project so I can pass on some cash to you.

Shelby
