### ISSUE TITLE
Extension not Compatible with Firefox 14.0.1 or 14.0.0

### ISSUE THREAD

**Issue by melban** [KangoExtensions/kango#2]
My extension is working fine with Firefox when installing the XPI file as long as I'm not building it when the 'update_path_url' setting is not set within extension_info.json.  When I am using the 'update_path_url' setting I keep getting the error message that my extension is not compatible with Firefox 14.0.1.   The extension can be found here for review.  http://pschrome.com/extension/ 

Here is my install.rdf with the ID blanked out.

<?xml version="1.0" ?><RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:em="http://www.mozilla.org/2004/em-rdf#">
    <Description about="urn:mozilla:install-manifest">
        em:id{ID}/em:id
        em:namePeopleSoft Helper Extension/em:name
        em:descriptionAutomation, visual enhancements and 3rd party tools/em:description
        em:version2.0.10/em:version
        em:targetApplication
            <Description>
                em:id{ID}/em:id
                em:minVersion3.6/em:minVersion
                em:maxVersion15.*/em:maxVersion
            </Description>
        /em:targetApplication
        em:creatorShelby Melban/em:creator
        em:homepageURLhttp://melban.me/extensions/peoplesoft-helper-extension/em:homepageURL
        em:updateURLhttp://pschrome.com/extension/update_firefox.xml/em:updateURL
        em:iconURLchrome://PeopleSoftHelperExtension_kango/content/icons/icon32.png/em:iconURL
    </Description>
</RDF>

**Comment by akrylysov** [comment]
Please take a look at http://kangoextensions.com/docs/general/autoupdating-extensions.html
Firefox requires https 'update_path_url'
