### ISSUE TITLE
Error (and Extension crash): "can't access dead object"

### ISSUE THREAD

**Issue by rafomundo** [KangoExtensions/kango#20]
KangoExtensions seems to have a huge problem with Firefox 16+,
i get always the following error and the extension stops working:

US: can't access dead object
@chrome://xxxxx_kango/content/includes/userscript_client.js:12
@chrome://xxxxx_kango/content/includes/userscript_client.js:11
@chrome://xxxxx_kango/content/includes/userscript_client.js:11
@chrome://xxxxx_kango/content/includes/invoke_async_module.js:15
@chrome://xxxxx_kango/content/includes/invoke_async_module.js:13
@chrome://xxxxx_kango/content/includes/invoke_async_module.js:15
@chrome://xxxxx_kango/content/kango/kango.js:12
@chrome://xxxxx_kango/content/kango/kango.js:14
@chrome://xxxxx_kango/content/kango/kango.js:20
@chrome://xxxxx_kango/content/kango/messaging.js:9

Mozilla said Firefox prevents the add-on from causing memory leaks:

http://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/

**Comment by akrylysov** [comment]
Plese give link to your XPI or send sources to extensions@kangoextensions.com

**Comment by akrylysov** [comment]
Could you please tell more about how you fixed "dead objects" issue?
