### ISSUE TITLE
Conflict with Google's "Mutation Summary" library

### ISSUE THREAD

**Issue by nadavsn** [KangoExtensions/kango#21]
Google's "Mutation Summary" library used to make DOM Mutation Observers simpler, just crashes Kango when it's loaded and executed. It's probably conflicting with Kango's own scripts.

On Google Code: http://code.google.com/p/mutation-summary/source/browse/mutation_summary.js

**Comment by akrylysov** [comment]
In which browser i can reproduce the issue?

**Comment by nadavsn** [comment]
Almost every browser, I used Firefox (16.0.2), as for Chrome I know mutation observers are supported from Chrome v18.

In my own source it was `@require`d in a content script. Once it was included, everything past it just didn't work, for example I tried to `alert('foobar')`.

**Comment by nadavsn** [comment]
Is anything found? I thought there's a way to separate the library from Kango, but I'm not sure how to do this

**Comment by akrylysov** [comment]
Our team a little bit busy right now, we will review this issue later.

**Comment by nadavsn** [comment]
I'll wait, no problem

**Comment by akrylysov** [comment]
Works fine in Kango 1.2.0.
