### ISSUE TITLE
Chrome Web Store: An error occurred: No manifest found in package. Please make sure to put manifest.json at the root directory of the zip package. 

### ISSUE THREAD

**Issue by braco** [KangoExtensions/kango#22]
Trouble uploading packages to both Chrome Web Store and Mozilla Add-ons.

From Chrome Store: "An error occurred: No manifest found in package. Please make sure to put manifest.json at the root directory of the zip package."

This is a very important problem to fix since vendors are moving toward app-store-only extension models. Kango is currently unusable for recent Chrome versions without manually editing the package, which is difficult because paths break if the manifest is moved to root.

**Comment by bnic** [comment]
Same issue with Chrome store.  Added manifest and fiddled with paths but no luck.

Zipping up the files inside the build/output/chrome folder worked.

**Comment by akrylysov** [comment]
Works fine, seems you doing something wrong, please send your .zip to extensions@kangoextensions.com

**Comment by braco** [comment]
@artemkrylysov: it happens with a default scaffold. manifest.json isn't in the root folder of the xpi package. Is this incorrect?

**Comment by bnic** [comment]
I zipped the chrome folder. Didnt use the packages

**Comment by akrylysov** [comment]
XPI is Firefox extension, you should zip output/chrome directory. If it doesn't help - please send zip to our email.

**Comment by braco** [comment]
This helped. Humbly suggest automatically zipping the folder and naming it chrome-webstore.zip, as all Chrome extensions need to follow this follow this distribution path now. Thanks!
