### ISSUE TITLE
dispatchMessage doesn't work in Chrome

### ISSUE THREAD

**Issue by RuudBurger** [KangoExtensions/kango#23]
The source for this problem can be found here: https://github.com/RuudBurger/CouchPotatoExtension

The problem seems to be when using the browserbutton and current tab. 
If I add a click event on the browserbutton that triggers this function:

`kango.browser.tabs.getCurrent(function(tab) {
      tab.dispatchMessage('showiFrame', 'data');
});`

It doesn't get fired in the content script in Chrome (works fine in Firefox).
The same kind of dispatchMessage from a function fired by TAB_CHANGED seems to work fine though.

**Comment by akrylysov** [comment]
Works fine for:

``` javascript
// background
kango.ui.browserButton.addEventListener(kango.ui.browserButton.event.COMMAND, function() {
    kango.browser.tabs.getCurrent(function(tab) {
        tab.dispatchMessage('showAlert', 'data');
    });
});

// content
kango.addMessageListener('showAlert', function(event) {
    alert(event.data);
});
```

What is your OS and browser version? Which URLs i should test?

**Comment by RuudBurger** [comment]
Ah man, I always hate when people don't add there version stuff and now I do it myself ;)
Chrome Version 23.0.1271.64 on OSX, like I said, the same code works in Firefox.

**Comment by RuudBurger** [comment]
Is it possible that Chrome has different scoping?
For example this seems to work in Firefox but not in Chrome:

```
var tab;
kango.browser.tabs.getCurrent(function(t){
    tab = t;
});
kango.console.log(tab) // Logs "Object" in Firefox, empty in Chrome
```

On a different note, logging is really hard when your used to Firebug :D. Is there a way to log the full object, so you see what is in it and not "[object Object]" or something like that.

Thanks btw for the nice framework, really easy to make something. Looking forward to more control on the button and browser UI :D.

**Comment by akrylysov** [comment]
kango.browser.tabs.getCurrent works asynchronously in Chrome so when you trying to use it - it is undefined. Try:

``` javascript
kango.browser.tabs.getCurrent(function(tab){
 kango.console.log(tab)
});
```

**Comment by RuudBurger** [comment]
Yeah that what I did after. Just would be nice to do `var tab = kango.browser.tabs.getCurrent()`, but I assume this is done because of some inner workings / browser differences.

**Comment by akrylysov** [comment]
Yes, it's a technical limitation of some browsers.

**Comment by RuudBurger** [comment]
Seems like it doesn't work with the opened tabs after installing the new crx file. Refreshing a tab doesn't work. Shutting down the tabs and opening a new one works. 
Thanks for the help though. This is closed for me as I can work around this issue ;)
