### ISSUE TITLE
kohls breaks Kango?

### ISSUE THREAD

**Issue by braco** [KangoExtensions/kango#24]
Default scaffold project with include: *

content.js never fires on kohls.com pages:

http://www.kohls.com/product/prd-1110266/ab-studio-striped-sweaterdress.jsp

It's very strange, can anyone confirm this? Crossrider seems ok.

**Comment by akrylysov** [comment]
Works fine for me. How can i reproduce it? What is your browser and OS versions? Please send us demo extension to extensions@kangoextensions.com
