### ISSUE TITLE
Bookmarks API?

### ISSUE THREAD

**Issue by 2is10** [KangoExtensions/kango#27]
Any plans to add a bookmarks API? Hoping for roughly what Chrome and Crossrider support: creating/reading/searching/moving/renaming bookmarks and bookmark folders.

Chrome: http://developer.chrome.com/extensions/bookmarks.html
Crossrider: http://crossrider.com/apps/17632/ide (see sample code in background.js)

I think Safari's the only browser that doesn't expose bookmarks in an API.

**Comment by akrylysov** [comment]
We don't plan add this feature because it's impossible to implement it on all browsers.
