### ISSUE TITLE
В Опере не работает require

### ISSUE THREAD

**Issue by Nafania** [KangoExtensions/kango#29]
Имеется ряд контент скриптов.
Один грузится всегда, другие только не определенных сайтах.
Который грузится всегда имеет в хедере
// @require jquery.1.8.3.min.js
После него грузятся скрипты для определенных сайтов.

В хроме и фаерфоксе все работает в норме, а вот опера ругается на
US: Undefined variable: $
И ничего не работает.

Куда копать?

**Comment by akrylysov** [comment]
You should add to beginning of your script:
var $ = window.$.noConflict(true);
See ChristmasTree sample https://github.com/KangoExtensions/kango-samples/blob/master/ChristmasTree/src/common/tree.js
