### ISSUE TITLE
access to kango.getExtensionInfo() from content script

### ISSUE THREAD

**Issue by gureedo** [KangoExtensions/kango#32]
I want to get ext version from content script, but `kango` object does not have method `getExtensionInfo()`. Is there a possibility to add such functional?

**Comment by akrylysov** [comment]
You can access only [some](http://kangoextensions.com/docs/general/content-scripts.html#kango-apis-available-in-content-scripts) APIs from content scripts. To access kango.getExtensionInfo from content script you should use [kango.invokeAsync](http://kangoextensions.com/docs/api-reference/kango.html#kango-invokeasync).
