### ISSUE TITLE
Got exception in Opera (Version 12.14) but in other browsers extension works

### ISSUE THREAD

**Issue by ramiisc** [KangoExtensions/kango#33]
US: Undefined variable: $
myExten([arguments not available])@
<anonymous function>([arguments not available])@
<anonymous function: evalInSandbox>([arguments not available])@content.js:13
<anonymous function: evalInSandbox>([arguments not available])@content.js:13
<anonymous function: executeScript>([arguments not available])@content.js:272
<anonymous function: run>([arguments not available])@content.js:265
<anonymous function: d.onSuccess>([arguments not available])@content.js:203
<anonymous function: kango.InvokeAsyncModule.prototype.init>([arguments not available])@content.js:169
<anonymous function: kango.InvokeAsyncModule.prototype.init>([arguments not available])@content.js:187
<anonymous function: opera.extension.onmessage>([arguments not available])@content.js:106

**Comment by sergpeganov** [comment]
I suppose you are using jQuery. There is some problem with $ definition in opera. Try add this code at the top of content.js:

var $;
if (typeof $ === 'undefined') {
    if (typeof window.$ !== 'undefined') {
        $ = window.$;
    } else {
        kango.console.log(['Error: could not load jQuery']);
    }
}

**Comment by ramiisc** [comment]
thanks. It is fixed

On 1 April 2013 18:28, sergpeganov notifications@github.com wrote:

> I suppose you are using jQuery. There is som problem with $ definition in
> opera. Try add this code at the top of content.js:
> 
> var $;
> if (typeof $ === 'undefined') {
> if (typeof window.$ !== 'undefined') {
> $ = window.$;
> } else {
> kango.console.log(['Error: could not load jQuery]);
> }
> }
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KangoExtensions/kango/issues/33#issuecomment-15714344
> .

## 

ramakrishna potluru.
