### ISSUE TITLE
Startup error on windows 

### ISSUE THREAD

**Issue by larrybek** [KangoExtensions/kango#34]
When I run Kango in python it brings 

usage: kango.py [-h] {create,build} ...
kango.py: error: too few arguments

Can somebody help with this

**Comment by akrylysov** [comment]
You should run kango.py with _create_ or _build_ argument, take a look at http://kangoextensions.com/docs/tutorials/gmail-checker.html

**Comment by larrybek** [comment]
Can you send me the code example how to write in python so it runs as even when I write d:\dev\kango\kango.py create it brings syntax error

**Comment by akrylysov** [comment]
What errors? Make sure you using Python 2.7.

**Comment by larrybek** [comment]
Im using Python 2.7.4 downloaded from website by link provided after adding the line in python idle its brings same error that I have mentioned before

**Comment by akrylysov** [comment]
You should run kango.py from command line, not from idle.

**Comment by larrybek** [comment]
Even from command line same result

**Comment by akrylysov** [comment]
Please show full console output.

**Comment by naddy0007** [comment]
Even i face the same issue

C:\Users\Saseennx\Desktop\kango-framework-latest>kango.py create c:\Users\Saseennx\Desktop\KangoProj
usage: kango.py [-h] {create,build} ...
kango.py: error: too few arguments

**Comment by akrylysov** [comment]
What is your Kango and Windows versions?
Try  to build one of samples in "sampes" durectory. Is it works?

**Comment by naddy0007** [comment]
Kango version V1.2.0
Windows version : Win7 enterprise

I tried running under the samples directory. Resulting in the same issue.

**Comment by akrylysov** [comment]
Could you please also try python.exe kango.py create c:\123?
What is your python version?

**Comment by naddy0007** [comment]
It worked :). Thank you very much. But i would like to know why I should do this way, rather than the one provided in the docs.
The python version is 2.7.4 (64-bit)

**Comment by akrylysov** [comment]
Very strange behaviour, maybe something wrong with your Python. We'll try to find the reason.
