### ISSUE TITLE
Firefox Icon does not stay past first install

### ISSUE THREAD

**Issue by melban** [KangoExtensions/kango#37]
I'm just now getting around to testing on firefox with my extension and when I install the XPI manually the Popup Icon shows just fine next to the home button.  If I close and reopen Firefox it is gone.  The extension still shows in the Add-ons and if I removed/readd it the same things happens.  I've created a new profile in Firefox and tested again with the same results.  If I use the firefox extension output directory as the source instead of the XPI I get the following error.  Also, although the icon does not show the other background and content scripts do work correctly.  

Warning: WARN addons.xpi: Add-on is invalid: Error: Directory C:\Temp\PSChrome3\extensions does not contain a valid install manifest
Source File: resource://gre/modules/XPIProvider.jsm
Line: 903

I'm on version 20.0.1 of Firefox on Windows 32 bit
I'm using Kango version 1.0.1
Python 2.7

I've also updated the install.rdf file to have a max version of 20.*
C:\frameworks\kango.1.0.1\src\js\firefox\install.rdf

**Comment by akrylysov** [comment]
Please try to reinstall Kango from http://kangoextensions.com/kango/kango-framework-latest.zip
