### ISSUE TITLE
Firefox 20 problem with kango.xhr

### ISSUE THREAD

**Issue by larrybek** [KangoExtensions/kango#38]
```
    method: 'POST',
    url: 'http://example.com/',
    async: true,
    params: {'param1': '1', 'param2': '2'},
    headers: {'If-Modified-Since': 'Sat, 1 Jan 2000 00:00:00 GMT', 'Cache-Control': 'max-age=0'},
    contentType: 'text'
```

};

kango.xhr.send(details, function(data) {
        if(data.status == 200 && data.response != null) {
                var text = data.response;
                kango.console.log(text);
        }
        else { // something went wrong
                kango.console.log('something went wrong');
        }
});

Running this function in extension on firefox20 doesn't display anything.

**Comment by akrylysov** [comment]
Are you executing this code from background or content script?

**Comment by larrybek** [comment]
Im using code from background as its in instruction

**Comment by larrybek** [comment]
Also have problem with integrating any json or jsonp files with ajax from other servers in content script same in firefox 20 its doesnt load anything.

**Comment by akrylysov** [comment]
Can't reproduce. Could you please provide sample URL and data?
