### ISSUE TITLE
JQuery's $ is undefined in Mozilla 20.01

### ISSUE THREAD

**Issue by rxtxup** [KangoExtensions/kango#39]
Kango Version: 1.2
Previous version seems okay.

Steps: edit file tree.js in sample https://github.com/KangoExtensions/kango-samples/blob/master/ChristmasTree/src/common/tree.js 
Adding lines below will produce an error:

if ( $.browser.mozilla ) {
  alert( $.browser.version );
}

Mozilla Firefox Mozilla 20.01 console:

US: $.browser is undefined
@resource://gre/modules/XPIProvider.jsm -> jar:file:///C:/Users/eugene/AppData/Roaming/Mozilla/Firefox/Profiles/nahd6ha2.default/extensions/%7B862FF4F2-E810-11E0-8FEF-D73D4824019B%7D.xpi!/bootstrap.js -> jar:file:///C:/Users/eugene/AppData/Roaming/Mozilla/Firefox/Profiles/nahd6ha2.default/extensions/%7B862FF4F2-E810-11E0-8FEF-D73D4824019B%7D.xpi!/kango/lang.js:27
@resource://gre/modules/XPIProvider.jsm -> jar:file:///C:/Users/eugene/AppData/Roaming/Mozilla/Firefox/Profiles/nahd6ha2.default/extensions/%7B862FF4F2-E810-11E0-8FEF-D73D4824019B%7D.xpi!/bootstrap.js -> jar:file:///C:/Users/eugene/AppData/Roaming/Mozilla/Firefox/Profiles/nahd6ha2.default/extensions/%7B862FF4F2-E810-11E0-8FEF-D73D4824019B%7D.xpi!/kango/lang.js:11

**Comment by akrylysov** [comment]
We have updated jQuery to version 1.9.1 in ChristmasTree sample. $.browser was removed from jQuery 1.9.0 ( http://api.jquery.com/jQuery.browser/). If you want, you can downgrade jQuery.

**Comment by akrylysov** [comment]
Btw, if you want yo know browser name, you can use [kango.browser.getName](http://kangoextensions.com/docs/api-reference/kango-browser.html#getname).
