### ISSUE TITLE
working with frames

### ISSUE THREAD

**Issue by gilkagan** [KangoExtensions/kango#4]
my addon is supposed to work on website with frames.
i dispatch an event as a result of another event and supposed to do something with the HTML
the listener is added for each frame matching the url pattern (all from a certain domain)

in Chrome, when i send the message, it is received by all frames, and then i can do some logic
in Firefox, however, the message is only received by the frame actually sending the original message

how can it be ? the event.target is the same tab for all frames. how come there is such a difference in Chrome and Firefox ?

thank you
Gil

**Comment by akrylysov** [comment]
Will be fixed in 1.0.

**Comment by akrylysov** [comment]
Fixed in 1.0.
