### ISSUE TITLE
Mozilla minVersion should be 12?

### ISSUE THREAD

**Issue by rxtxup** [KangoExtensions/kango#40]
I'm getting error, trying to install new xpi built with Kango 1.2 in Firefox under 12.0
Timestamp: 10.05.2013 10:53:38
Warning: WARN addons.manager: Exception calling callback: TypeError: b is undefined
Source File: resource:///modules/XPIProvider.jsm -> jar:file:///C:/Users/eugene/AppData/Roaming/Mozilla/Firefox/Profiles/nahd6ha2.default/extensions/%7B162516c0-2c2f-11e1-8be3-005056c00008%7D.xpi!/bootstrap.js -> jar:file:///C:/Users/eugene/AppData/Roaming/Mozilla/Firefox/Profiles/nahd6ha2.default/extensions/%7B162516c0-2c2f-11e1-8be3-005056c00008%7D.xpi!/kango/storage.js
Line: 17

Extension marks itself compatible with minVersion 8.0 (taken from install.rdf)

**Comment by rxtxup** [comment]
It seems Services.scriptSecurityManager and Services.domStorageManager in storage.js was added to FF since version 12.0 only.

**Comment by akrylysov** [comment]
Thank you for report. Firefox 8 compatibility issues fixed. You can download the latest version from our website.
