### ISSUE TITLE
Content script do not injects into image preview tab (Mozilla)

### ISSUE THREAD

**Issue by rxtxup** [KangoExtensions/kango#41]
Test tab: http://top-page.appspot.com/static/img/simple.png

Seems like when any image file opened in new tab DOMContentLoaded event listener in "kango-framework-1.2\src\js\ie firefox\kango\userscript_engine.part.js" has never called.

**Comment by akrylysov** [comment]
Not a bug. We support content script injection only on web pages.

**Comment by rxtxup** [comment]
@artemkrylysov It's a valid web page with head and body. The other tools like Chrome content scripts and Mozilla Addon SDK support this.

**Comment by akrylysov** [comment]
We are trying to implement features that are supported in 5 browsers, but it's technically impossible to inject content scripts on image pages in Opera. Anyway thank you for your report we will consider this feature in upcoming version.

**Comment by akrylysov** [comment]
Will be fixed in Kango 1.3.0.
