### ISSUE TITLE
Opera extension always requests access to *

### ISSUE THREAD

**Issue by oliversalzburg** [KangoExtensions/kango#42]
I tried to publish an extension to the Opera repository and they notified me that it requests access to all websites, even when a small subset would suffice.

The [access](http://dev.opera.com/articles/view/extensions-api-config-access/) element is set to `*`

I would have expected that node to be populated by the `@include` directives in my JS file.

**Comment by oliversalzburg** [comment]
Sorry, made a mistake. It seems like the reviewer was referring to the `content.js` file only. He added later

> You need to add:
> // ==UserScript==
> // @include
> // ==/UserScript==
> to that file manually.

**Comment by akrylysov** [comment]
As workaround you can add this header manually to content.js.
Opera 15 switched to Chromium's extension format and no longer supported Opera 11 & 12’s extensions (http://dev.opera.com/extension-docs/).
