### ISSUE TITLE
Mozilla extension submission problems with AMO team

### ISSUE THREAD

**Issue by rxtxup** [KangoExtensions/kango#43]
I just got:
"Our current policy on Kango add-ons is to only accept unmodified versions of the Kango framework which have been sent to us by its maintainers for review prior to submission. Unfortunately, the version of the Kango framework that you include does not match known checksums for any such submission and therefore cannot be accepted at this time. Please contact the Kango team if you need help obtaining an approved version."
The problem is even if they will get the latest version, I still need to change one module of Kango framework for my needs

**Comment by akrylysov** [comment]
AMO team still reviewing new version of our Kango, please wait some time.

> The problem is even if they will get the latest version, I still need to change one module of Kango framework for my needs

Could you please tell more? I think we can find the solution.

**Comment by rxtxup** [comment]
Created issue for this here:
https://github.com/KangoExtensions/kango/issues/44

**Comment by rxtxup** [comment]
What is the last approved version?

**Comment by akrylysov** [comment]
1.0.1

**Comment by melban** [comment]
I just received that message from the Mozilla team also.  Please let us know when 1.2.0 gets its approval.  Thanks.

**Comment by rxtxup** [comment]
Not sure which version to use: 1.2 released May, 8 or the latest from kango site?

**Comment by oliversalzburg** [comment]
Oh damn, I currently have something up for review at Mozilla as well. I guess I know the outcome of that now :D

Publishing Chrome extensions is more fun ;P

**Comment by akrylysov** [comment]
We have made some AMO related fixes and i hope we will be able to release the new Kango version at the beginning of the next week.

**Comment by akrylysov** [comment]
We have fixed all AMO related issues and passed review. You can download Kango 1.2.1 from website.

**Comment by rxtxup** [comment]
OMG, we waited 25 days for Preliminary review and again got this:

Your add-on has been reviewed by an editor and did not meet the criteria for being hosted in our gallery.

Reviewer:
Kris Maglione

Comments:
Your version was rejected because of the following problems:

1) We can't match your included version of Kango to the checksum of any known version. Please include only releases of libraries obtained from official sources in their original, unmodified files. Please note that third party CDNs are not considered official sources for this purpose.

Please fix them and submit again. Thank you.

This version of your add-on has been disabled. You may re-request review by addressing the editor's comments and uploading a new version. To learn more about the review process, please visit https://addons.mozilla.org/developers/docs/policies/reviews#selection

## If you have any questions or comments on this review, please reply to this email or join #amo-editors on irc.mozilla.org

Mozilla Add-ons
https://addons.mozilla.org

**Comment by oliversalzburg** [comment]
Weird, my Kango Framework based extension was reviewed and accepted by AMO yesterday.

**Comment by akrylysov** [comment]
@rxtxup could you please give me a link to your XPI?

**Comment by rxtxup** [comment]
@artemkrylysov beta.favim.com/media/static/data/favimcom_1.0.9.xpi

**Comment by akrylysov** [comment]
@rxtxup your extension built on Kango 1.2.0, AMO fixes was made in Kango 1.2.1.

**Comment by rxtxup** [comment]
@artemkrylysov Thanks, it's my issue.

**Comment by kambanthemaker** [comment]
Hi, Thanks. Is 1.2.4 version be compatible with firefox store ?

**Comment by melban** [comment]
@selvamarcadu When I asked in the past Artem has said yes.

**Comment by jessedepril** [comment]
Version 1.2.5 isn't compatible with the firefox store.

**Comment by akrylysov** [comment]
You must use 1.2.4 from website or 1.2.6 from customer dashboard (for commercial package).

**Comment by panzerdp** [comment]
Hi. How about latest 1.3.1 version, it can be used already for publishing in Firefox store?
Thanks.

**Comment by akrylysov** [comment]
Yes, take a look at https://github.com/mozilla/amo-validator/pull/212.
