### ISSUE TITLE
Context menu item icon in mozilla extension

### ISSUE THREAD

**Issue by rxtxup** [KangoExtensions/kango#44]
Hi, is it possible to add icon and position properties for context menu icon in the "src\js\firefox\kango-ui\context_menu.js" ?
Currently I use some hard coded lines below, but I assume it will cause problems with framework files checksums?
  addItem: function(a, b, c, g) {
    ...

```
// Item Icon.
e.className = 'menuitem-iconic';
var contextIconPath = '/content/icons/button.png';

var fullPath = "chrome://kango-" + kango.utils.getDomainFromId(kango.getExtensionInfo().id) + contextIconPath;

e.setAttribute('image', fullPath);

...

// The item will be after Save Image item.
var myElement = d.getElementById(b);
var insertAfter = d.getElementById("context-saveimage");
if (myElement && insertAfter) insertAfter.parentNode.insertBefore(myElement, insertAfter.nextSibling);
```

  }

**Comment by akrylysov** [comment]
Please contact me artem@kangoextensions.com and i'll tell you how to extend framework functionality (this abilities in beta stage and not documented yet).
