### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by kfatehi** [KangoExtensions/kango#45]
Nice framework. I was hoping to find the source code here on github so I could make a pull request that adds coffeescript as an optional build step.

for example, the self = this that goes into the boilerplate is completely unnecessary if Kango embraces CoffeeScript as a build step.

**Comment by kfatehi** [comment]
Ok I got this working pretty well. I'll gemify it and add a link here.

➜  test git:(master) ✗ rake kango:install
Downloading Kango Framework to kango-framework.zip...
Download complete! Extracting...
Kango Framework is ready. You can now rake build
➜  test git:(master) ✗ rake build
[   INFO] Compiling src/coffee/github.coffee to src/common/github.js
[   INFO] Compiling src/coffee/main.coffee to src/common/main.js
[   INFO] Kango browser extension builder started
[   INFO] Contact extensions@kangoextensions.com to enable IE support
[   INFO] Building chrome extension...
[   INFO] Building firefox extension...
[   INFO] Building opera extension...
[   INFO] Building safari extension...
➜  test git:(master) ✗

**Comment by kfatehi** [comment]
Gem built.

Available on rubygems http://rubygems.org/gems/kango
Source is here https://github.com/keyvanfatehi/kango

Basically people can use this to install kango itself, and create a kango project (calls kango.py), and it bootstraps them with a coffee directory that includes a coffeescript version of the main.js:

``` coffeescript
MyExtension = ->
  kango.ui.browserButton.addEventListener kango.ui.browserButton.event.COMMAND, =>
    @._onCommand()

MyExtension:: = _onCommand: ->
  kango.browser.tabs.create url: "http://kangoextensions.com/"

extension = new MyExtension()
```

Short and sweet.

Users can then call "kango build" which produces the output you saw in my last comment.

It works well with userscripts, converts them nicely to valid javascript usersscripts... As I build more advanced extensions (hopefully I get time to do this... Kango motivates that I can do it quicker though), I will do it with my gem and support more complicated setups.

Hope you like it. Closing the issue.

**Comment by akrylysov** [comment]
Thank you. It's also can be done using custom build steps, we will introduce it later.

**Comment by kfatehi** [comment]
OK I will reopen it for you, since this isnt a fix to Kango, but a ruby wrapper. Let me know if I can help in any way further -- I was reluctant to write code in Kango source without the code being in a repo, so I just wrapped it and it downloads Kango from your website when users do `kango install`

**Comment by kfatehi** [comment]
I guess if the wrapper does the job, there's more important things than coffeescript--like live reload :)
