### ISSUE TITLE
Auto reload while developing

### ISSUE THREAD

**Issue by kfatehi** [KangoExtensions/kango#47]
I came across this article for Chrome http://stackoverflow.com/questions/2963260/how-do-i-auto-reload-a-chrome-extension-im-developing

But I am curious if there's a recommended way to this with Kango, e.g. a one-line switch that puts the thing in development mode with autoload features? (i.e. you're develping a web application like in Rails, and if you hit a route it will reload your new source code changes).

In the meanwhile I will look into solving this with the ruby wrapper (watch filesystem events and perform autobuilds)

**Comment by akrylysov** [comment]
You can auto reload Firefox extension: https://addons.mozilla.org/en-US/firefox/addon/autoinstaller/
We are going to make such abilities for all browsers in next versions.

**Comment by kfatehi** [comment]
Cool, if you tell me about them I can prepare better. It looks like livereload is pretty nice for this and ruby developers have made guard-livereload, making development pleasant -- I'll try to work these into the Kango rubygem... will need to write some specs now that it must grow.

I am considering adding command 'kango watch' for this purpose.

**Comment by kfatehi** [comment]
I've updated my gem to 0.0.3.0.9.2 and added `kango watch` which will auto compile coffeescript files and auto build files in src/common that have changed. In addition if you do `kango watch reload.extensions` it will point Chrome Canary to http://reload.extensions (requires ExtensionsReloader chrome extension).

works pretty well and can be extended with other reloaders, if you see the way i've coded it.

Anyway this works for me so closing this issue, thanks!

**Comment by scancel** [comment]
If anyone is looking for @kfatehi gem in a windows version, you can find it here: 
https://github.com/scancel/kango/commit/31f8fee857f2b3e9dba09fe383157739d5ec2eed
