### ISSUE TITLE
firefox use icon48.png as popup button icon.

### ISSUE THREAD

**Issue by alexyutmp** [KangoExtensions/kango#48]
my icons folder contains button.png (which is 16x16 img), and also contains icon32.png,icon48.png,icon100.png,icon128.png, firefox somehow doesn't use button.png as popup icon,

my kango extension framework is 1.2

**Comment by akrylysov** [comment]
Did you tried to set icon using browser_button.icon (http://kangoextensions.com/docs/api-reference/KangoExtensionInfo.html) property?

**Comment by alexyutmp** [comment]
thanks, it solves the issue!
