### ISSUE TITLE
kango popup html doesn't work on MacOS with obfuscated js

### ISSUE THREAD

**Issue by alexyutmp** [KangoExtensions/kango#49]
the error shows on console, but it works on windows
timestamp: 13-5-27 下午4:24:49
Error： NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: '[JavaScript Error: "this.xulwin is undefined" {file: "jar:file:///Users/xxxxx/Library/Application%20Support/Firefox/Profiles/xex554s9.default/extensions/tabnotifier@unusoft.it.xpi!/components/nsTnNotificationCenter.js" line: 162}]' when calling method: [nsIDOMGlobalPropertyInitializer::init]
SRC：chrome://extensionidhere/content/popup.js
行：1

**Comment by akrylysov** [comment]
Please send us sample extension to extensions@kangoextensions.com

**Comment by alexyutmp** [comment]
I don't know if I could trip the script and send to you, but here is the clue,
I'm using this inside background js, for macos, firefox doesn't support showAlertNotification,the erro maybe related to this? :
var alertsService = Components.classes["@mozilla.org/alerts-service;1"].getService(Components.interfaces.nsIAlertsService);
        alertsService.showAlertNotification(iconpath, 
                                            title, content, 
                                            true, link, listener, "");

**Comment by akrylysov** [comment]
Hard to say, we need a way to reproduce the issue (e.g. your compiled extension).

**Comment by ehtao** [comment]
ok, I found that if I restart firefox, the issue will gone
