### ISSUE TITLE
Options page?

### ISSUE THREAD

**Issue by katspaugh** [KangoExtensions/kango#5]
In Chrome extensions you can specify the options page (visible from the Chrome extensions manager). See http://developer.chrome.com/extensions/options.html

Is it going to be supported in Kango framework?

**Comment by akrylysov** [comment]
Will be implemented in next versions. Right now you can use remote HTML and content script to make options.

**Comment by akrylysov** [comment]
You can download new version at http://kangoextensions.com/kango/kango-0.9.9-public.zip

## Settings API

Settings API in beta stage now and it's not documented.

To enable Options page you should add "options_page" key to extension_info.json.
HTML page should be named "options.html".
You can open Options page programmatically: kango.ui.optionsPage.open();

Example:
extension_info.json::
{
    ...
    "options_page": "options.html",
    ...
}

main.js::
kango.ui.browserButton.addEventListener(kango.ui.browserButton.event.Command, function(event) {
    kango.ui.optionsPage.open();
});

options.html::

<script type="text/javascript" src="kango-ui/kango_api.js"></script>

options.js::
KangoAPI.onReady(function() {
    // read settings, etc
});

Note: Kango API available only in async mode (as in content scripts).

## Changes in content scripts
- Content scripts don't runs on iframes by default anymore. To enable iframe content scripts you should add "@all-frames true" to user script header key.
- To include JS libraries you should use @require user script header key (see ChristmasTree).
