### ISSUE TITLE
Incompatible with Firefox 21

### ISSUE THREAD

**Issue by deepesh-agarwal** [KangoExtensions/kango#52]
My addon which worked fine with earlier Kango version for both Firefox and Chrome, is only working on Chrome now - any ideas  what could be the reason ?

**Comment by akrylysov** [comment]
Please send me compiled XPI artem@kangoextensions.com

**Comment by deepesh-agarwal** [comment]
Sent...

**Comment by akrylysov** [comment]
Change your @require key in content.js to:

> // @require jquery.min.js
