### ISSUE TITLE
TAB_CHANGED event should also fire on switch back from different tab

### ISSUE THREAD

**Issue by martinth** [KangoExtensions/kango#53]
If you swtich between tabs is works fine, however, consider this flow of events:
- user open another browser window, does some work an closes it again
- original tab regains focus but TAB_CHANGED is not fired for this tab

I'm using an object in the background script to keeb track of all tabs where I have modified the DOM (via a CS) to Toggle the browser Icon (so the user can revert the changes). I use TAB_CHANGED to keep track of which tabs the user has currently open so the state of the button always represents the state of the page. Without that TAB_CHANGED on window changes the button get "out of sync".

**Comment by martinth** [comment]
Alternatively I would life with a WINDOW_CHANGED event, or even better, a TAB_FOCUSED event.

**Comment by akrylysov** [comment]
Thank you for report, we will provide you a solution today or tomorrow.

**Comment by akrylysov** [comment]
We have implemented WINDOW_CHANGED event. New Kango version will be released on beginning of the next week.

**Comment by akrylysov** [comment]
You can use WINDOW_CHANGED event in Kango 1.2.4:

``` javascript
kango.browser.addEventListener(kango.browser.event.WINDOW_CHANGED, function(event) {
    kango.console.log('Window Changed');
    event.target.getCurrentTab(function(tab) {
        kango.console.log(tab.getUrl());
    });
});
```

**Comment by vikask** [comment]
I'm using "chrome.tabs.onUpdated.addListener()" in chrome on update tab. How can i use in kango tab on update like chrome tab ("chrome.tabs.onUpdated.addListener()") ?

**Comment by akrylysov** [comment]
This event type is not supported by Kango.
