### ISSUE TITLE
Refreshing the options page in IE never fires KangoAPI.onReady

### ISSUE THREAD

**Issue by smartvault-abbott** [KangoExtensions/kango#54]
User hits refresh in the options page, KangoAPI.onReady is never fired, so kango object is never created.

This only seems to be a problem in IE.  Tested in IE10, but I suspect it's the same behavior in other versions.  Firefox and Chrome worked fine.

**Comment by akrylysov** [comment]
Issue is fixed, new Kango version will be released on beginning of the next week.
