### ISSUE TITLE
window.open not working inside $(document).bind("unload") event since 1.2.0

### ISSUE THREAD

**Issue by darko-m** [KangoExtensions/kango#56]
Hello,
I have ff extension that uses $(document).bind("unload") on extension side to catch browser closing event and then, if needed, open new window using window.open.
It worked with 1.0.0 and doesn't work since 1.2.0. Should I change something in extension_info.json? I have simple text example extension compiled xpi files for both 1.0.0 and 1.2.0 demonstrating issue if needed.
Thanks.

**Comment by akrylysov** [comment]
Please send us demo extension to extensions@kangoextensions.com

**Comment by darko-m** [comment]
Any info on this matter? Did you get demo extenstions?
Extension mentioned is comercial product and this is important issue for us that will determine if we should use Kango for our extension at all. 
Thanks.

**Comment by akrylysov** [comment]
Not an issue, if you will purchase commercial license, we will provide you a workaround.
