### ISSUE TITLE
IE 8/9 browser cookies get overwritten when calling kango.xhr.send

### ISSUE THREAD

**Issue by brianshome** [KangoExtensions/kango#57]
It seems that when invoking kango.xhr.send to make an ajax request for a given domain, the cookies of the domain get overwritten and tagged with httpOnly. This prevent the javascript on the domain from reading the cookies. 

Looking at the kango generated javascript, under ie/kango/xhr.js, there are logic to exipre the cookies and rewrite them with new expiration date. This seems to happen only for IE and not the other browsers. Is there a particular reason that kango is doing so for IE?

**Comment by akrylysov** [comment]
Please email us extensions@kangoextensions.com and we will provide you solution.
