### ISSUE TITLE
Tabs API in popup doesn't work (chrome)

### ISSUE THREAD

**Issue by gsobczyk** [KangoExtensions/kango#59]
I cannot redirect user to new page from popup in chrome.
When I click item in popup i this extension - it do nothing
https://github.com/gsobczyk/create-rt-ticket

**Comment by melban** [comment]
If the link it hard coded in the HTML of your popup page you can try setting a target such as "_blank".  If you are using JavaScript to generate the link or assign a click function then you can use kanog.invokeAsync() to call the tabs API.

kango.invokeAsync( 'kango.browser.tabs.create', {url:'http://example.com/'} );

http://kangoextensions.com/docs/api-reference/kango.html#kango-invokeasync
http://kangoextensions.com/docs/api-reference/kango-browser-tabs.html#kango-browser-tabs-create

**Comment by gsobczyk** [comment]
no, it doesn't help, try: https://github.com/gsobczyk/create-rt-ticket/tree/chrome-test
in popup.html there are:

``` javascript
function testChrome(){
    kango.browser.tabs.getCurrent(function(tab) {
        kango.invokeAsync('kango.browser.tabs.create', {url:'http://o2.pl'} );
    }
}
```

**Comment by melban** [comment]
The errors I see when clicking on the popup icon.

By default Kanog limits the content_security_policy is below.  I add google analytics so I change "kango.1.2.4\src\js\chrome\manifest.json" to include the Custom line.  

For the 2nd error I don't think you can include inline scripts or event attributes like 'onclick', 'onchange'.  You need to create a popup.js which would attach a click event to the HTML Element.  All JavaScript execution has to be in your JS files not within `<script>` tags on the popup.html

Default

```
"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'", 
```

Custom

```
,"content_security_policy": "script-src 'self' https://*.google-analytics.com 'unsafe-eval'; object-src 'self'"
```

Errors

```
Refused to load the script 'http://twitter.github.com/hogan.js/builds/2.0.0/hogan-2.0.0.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'".

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'".
```

 popup.html:26

**Comment by akrylysov** [comment]
Thank you for answers, @melban.

Chrome doesn't allow inline scripts:
1. You have to put them in a separate JS file.
2. You must use native addEventListener or jQuery to attach "click" event.

Chrome doesn't allow remote scripts. You must put hogan-2.0.0.js in your extension package.
