### ISSUE TITLE
JavaScrit and CSS before load

### ISSUE THREAD

**Issue by christianromeni** [KangoExtensions/kango#6]
Is there going to be a way tom implement JS and CSS before the website is completely loaded?
I would like to modify a website, but the old style would be displayed before, and I dont want that.

**Comment by akrylysov** [comment]
Impossible in v0.9.8, but we will add ability to run content scripts before DOMContentLoaded event in future versions.

**Comment by christianromeni** [comment]
Good to hear that... Do you have an estimate when this will happen?

**Comment by akrylysov** [comment]
No exact ETA right now (we need some research work in IE and FF), will update this issue when some details will be available.

**Comment by christianromeni** [comment]
That would be really great.... If this is available I'll use Kango for my Projects....Even if IE is left out for the moment :)

**Comment by krutikashah** [comment]
Any updates? I was looking for a way to be able to intercept and/or block  resource requests before the DOMContentLoaded event.  
Thanks

**Comment by akrylysov** [comment]
> Any updates? I was looking for a way to be able to intercept and/or block resource requests before the DOMContentLoaded event.

Not implemented yet, but you will not be able to intercept and/or block resources even if you can load your content script before DOMContentLoaded.

**Comment by akrylysov** [comment]
Implemented for Chrome, Firefox, Opera, Safari in Kango 1.3.0.

**Comment by christianromeni** [comment]
Finaly!!! Top! :) Thx a lot.

**Comment by akrylysov** [comment]
You are welcome, new version will be avaliable in two weeks.

**Comment by garoevans** [comment]
Is there any documentation on how to do this? I have the following but it doesn't seem to do what I wanted:

```
{
    "content_scripts": [
        {
            "js": "initiate.js",
            "run_at": "document_start"
        },
        "listener.js"
    ],
```

UPDATE:

Think I found it `@run-at document-start`
