### ISSUE TITLE
contextMenuItem click not passing srcURL in kango.Event

### ISSUE THREAD

**Issue by melban** [KangoExtensions/kango#61]
The contextMenuItem event isn't passing the source url on the background page.  

I do not yet see documentation on kango.ui.contextMenuItem but I found the example in the 1.2.4 samples.  

Chrome: Version 29.0.1547.57 m
Kango 1.2.4
OS: Windows XP

Background page code
    kango.ui.contextMenuItem.addEventListener(kango.ui.contextMenuItem.event.CLICK, function(e) {
        console.log( e );
        //PSChrome.storage.setItem( PSChrome.optionsPageChange, myURL.id );
        kango.ui.optionsPage.open('tabs-environments');
    });

Returned Value
kango.Event {type: "click", target: null, result: null, srcUrl: undefined, linkUrl: undefined}

**Comment by akrylysov** [comment]
You can detect srcURL from content script, take a look at https://github.com/KangoExtensions/kango-samples/tree/master/ContextMenuItem/src/common
