### ISSUE TITLE
Kango can't build safari extention.

### ISSUE THREAD

**Issue by ghost** [KangoExtensions/kango#66]
The certificate is under certificates folder but kango can't create an extention. 

But the bin folder contains the safari folder with code and the developer id is in bin/safari/extension_info.json.

I try to load the extention in safari but get that the developer certificate is missed.
Also kango can't create a 'zipped' extention. The extention is just in the bin folder.

This 2 line are in bin/safari/extension_info.json
"developer_id": "{FOO24BAR}", 
"kango_version": "1.2.4 744e69cf4136", 

(for sure the developer_id here is not the one i use)

I use ubuntu.
Is there a manual, a how to do or something else, maybe i do things wrong?

**Comment by akrylysov** [comment]
You must build Safari extension manually, take a look at https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/UsingExtensionBuilder/UsingExtensionBuilder.html
