### ISSUE TITLE
An exception in Opera when opening a new Window

### ISSUE THREAD

**Issue by wiz00** [KangoExtensions/kango#67]
Using

<code>kango.browser.windows.create({url:someUrl});</code>

throws an Exception in Opera in this function:

src/js/opera/kango/browser.part.js:
<code>create:function(a){opera.extension.windows.create().tabs[0].url=a.url}}</code>

<code>opera.extension.windows.create()</code> returns an Object with read-only field <code>tabs</code>.
First tab URL should be passed as an argument, like so:
<code>opera.extension.windows.create({url:[a.url]})</code> according to documentation.

But it still doesn't work for me (new window is just blank).

Would you fix that?

Thank!

**Comment by akrylysov** [comment]
We don't support Opera 12 anymore. Opera 12 support will be removed in Kango v1.3.0.
