### ISSUE TITLE
No tab with id: ...

### ISSUE THREAD

**Issue by ghost** [KangoExtensions/kango#68]
I get an error with the current BrowserEvents example from kango samples folder and current Chrome version 30. (Also with older Chrome versions)

I restart my browser and open a new tab. 
Then, I type "google.de" in the browserbar and hit enter. 
After a search for "kango" I get an error that a tab id not exist. 

If the error occurs the extension breaks for the current tab.

It seems kango tries to get a  tab, that wasn't created before: 

chrome://extensions/ console.js:1
Tab Created
Target tab url=chrome://newtab/
Tab id=16 console.js:1
Tab Changed
Target tab url=chrome://newtab/
Tab id=16 console.js:1
BeforeNavigate
Url=chrome://newtab/
Is tab active=true console.js:1
DocumentComplete
Url=chrome://newtab/
Title=New Tab
Is tab active=true console.js:1
BeforeNavigate
Url=http://google.de/
Is tab active=true console.js:1
DocumentComplete
Url=https://www.google.de/
Title=Google
Is tab active=true console.js:1
tabs.get: No tab with id: 18.
    at Object.kango.Browser.kango.oop.extend._onBeforeNavigate (chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/browser.js:18:18)
    at chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/utils.js:6:216 lastError:29
tabs.get: No tab with id: 18.
    at Object.kango.Browser.kango.oop.extend._onDOMContentLoaded (chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/browser.js:18:262)
    at chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/utils.js:6:216 lastError:29
tabs.get: No tab with id: 18.
    at Object.kango.Browser.kango.oop.extend._onBeforeNavigate (chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/browser.js:18:18)
    at chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/utils.js:6:216 lastError:29
tabs.get: No tab with id: 18.
    at Object.kango.Browser.kango.oop.extend._onDOMContentLoaded (chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/browser.js:18:262)
    at chrome-extension://nknlfhnkkcgjhncbmdkijajnlfnjomik/kango/utils.js:6:216 lastError:29

What can I do to prevent the error?

**Comment by ghost** [comment]
There are updates? I still get the error with the example. I open a new tab and write something in the address bar, before I hit enter, I get the error:

Tab Created
Target tab url=chrome://newtab/
Tab id=174 console.js:12
Tab Changed
Target tab url=chrome://newtab/
Tab id=174 console.js:12
BeforeNavigate
Url=https://www.google.com/_/chrome/newtab?espv=2&ie=UTF-8
Is tab active=true console.js:12
DocumentComplete
Url=https://www.google.com/_/chrome/newtab?espv=2&ie=UTF-8
Title=New Tab
Is tab active=true console.js:12
Unchecked runtime.lastError while running tabs.get: No tab with id: 176.
    at Object.object.extend._onBeforeNavigate (chrome-extension://bfbdbkiidmjkagdicidjnklnijpknbjj/kango/browser.js:20:113)
    at chrome-extension://bfbdbkiidmjkagdicidjnklnijpknbjj/kango/utils.js:13:391 extensions::sendRequest:86
Unchecked runtime.lastError while running tabs.get: No tab with id: 176.
    at Object.object.extend._onNavigationCompleted (chrome-extension://bfbdbkiidmjkagdicidjnklnijpknbjj/kango/browser.js:20:337)
    at chrome-extension://bfbdbkiidmjkagdicidjnklnijpknbjj/kango/utils.js:13:391 extensions::sendRequest:86

**Comment by akrylysov** [comment]
The issue doesn't break the extension anymore.
