### ISSUE TITLE
Feature Request: Add button inside urlbar

### ISSUE THREAD

**Issue by RuudBurger** [KangoExtensions/kango#69]
I would love to have feature where you can add the button to the urlbar like the Flattr extension for example:

![screen shot 2013-11-12 at 22 44 57](https://f.cloud.github.com/assets/38136/1526388/b9afeb3c-4be3-11e3-9ee2-71a82057036f.png)

**Comment by akrylysov** [comment]
Unfortunately it's impossible to implement this feature in all browsers.
