### ISSUE TITLE
Capture hotkeys/keyboard shortcuts?

### ISSUE THREAD

**Issue by g2010a** [KangoExtensions/kango#70]
Hi, 

Is it possible to capture hotkeys / keyboard shortcuts other than by using a keyup listener on a content script?  (this tends to break if the focus is on, say, Google's text input, which does not trigger the keyup event)

**Comment by akrylysov** [comment]
Kango doesn't have a built-in key capture functionality, but you can use any JS library. Take a look at https://github.com/jeresig/jquery.hotkeys
