### ISSUE TITLE
permissions.context_menu is not working

### ISSUE THREAD

**Issue by HarryLyu** [KangoExtensions/kango#71]
Passing permissions into /src/common/extension_info.json, for example:
"permissions": {
...
    "context_menu": true,
...
}
will not pass proper permissions in builded extension in manifest.json

**Comment by HarryLyu** [comment]
Cane be fixed by adding 
"context_menu_item": true
to extension_info.json

What does "context_menu_item" param mean?

**Comment by akrylysov** [comment]
ContextMenu API is not documented, but you can find sample at https://github.com/KangoExtensions/kango-samples/tree/master/ContextMenuItem/src/common
