### ISSUE TITLE
Encoding erros in build on Windows for IE

### ISSUE THREAD

**Issue by HarryLyu** [KangoExtensions/kango#74]
Trying to build extension with Kango 1.3.1 on Windows 7 64bit with Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win32

And error comes from russian locale files after installing extension in IE10 (http://joxi.ru/ImmOUtg5CbCoISMApR4):
http://joxi.ru/82aOUtg5CbD-H7eCPIQ
http://joxi.ru/CGeOUtg5CbBSIRPD4xY

All files are in UTF-8.

I can give you an access to GitHub repo with extension if you need it for tests.

**Comment by akrylysov** [comment]
Please try to resave files in "UTF-8 with BOM" encoding.

**Comment by HarryLyu** [comment]
Thanks, it works for me!
