### ISSUE TITLE
Error in event handler for (unknown): ReferenceError: KangoAPI is not defined

### ISSUE THREAD

**Issue by mabdelfattah** [KangoExtensions/kango#76]
I get this error using https://chrome.google.com/webstore/detail/jccedjlgpejonihonobakljablgoimio
on all pages, for example this one:
http://shop.vodafone.com.eg/smart-phones/lg-optimus-l3-e400/

But I can't trace what is the cause of the error, how could I know?!

**Comment by akrylysov** [comment]
Please describe your issue more detailed and send us sample source code.

**Comment by mabdelfattah** [comment]
@artemkrylysov Please send me your bitbucket username and I'll add you to the source code repo.

Or just install the extension and you can find the source code.

**Comment by akrylysov** [comment]
Sorry, we don't provide premium support for free. Please send us sample source code (not whole project) and we will try to help you.

**Comment by mabdelfattah** [comment]
Sorry, I knew the problem.

It was including popup.js in the background files list in extension_info.json file
