### ISSUE TITLE
Popup window in Firefox 26 & Windows 8

### ISSUE THREAD

**Issue by panzerdp** [KangoExtensions/kango#78]
Hello kango team.
I have a problem using popup window in Firefox 26, Windows 8.
The popup itself opens correct when clicking on browser button, but when I'm scrolling, the content disappears. After waiting about 2-3 seconds it appears again.
In chrome it works correct. With Firefox 26 in Windows 7 and Ubuntu works well too.
Used kango 1.2.4 and 1.3.1.
Thank you.

**Comment by akrylysov** [comment]
Please send compiled extension to extensions@kangoextensions.com
