### ISSUE TITLE
Kango IE extension

### ISSUE THREAD

**Issue by Aitamer** [KangoExtensions/kango#81]
I'd like to buy a kango license in order to run my extension on IE. Can you tell me if the IE kango framework version works and if I can buy it. I have already sent a message from the web site kangoextensions.com but no answer.
Best regards

**Comment by 3000** [comment]
Hi Artem,

I've also emailed via the site and direct to extensions@kangoextensions.com enquiring about commercial license with no response for a couple of days.  Just wondering if its still possible to acquire the IE/Commercial License?

Regards

**Comment by akrylysov** [comment]
We are very sorry, but we currently don't provide commercial version of Kango.

**Comment by 3000** [comment]
Ok great so there is no way to get Internet Explorer support through Kango now?

**Comment by akrylysov** [comment]
Right.

**Comment by toddcarper** [comment]
So, is there a way to get the 1.3.5 with the few fixes for IE?

**Comment by akrylysov** [comment]
Hello, @toddcarper you can download the latest version from your dashboard.

**Comment by TheRubble** [comment]
Can I ask why you don't offer IE anymore? It's potentially a show stopper for my project. Is it for technical reasons?

**Comment by akrylysov** [comment]
No, it's not a technical reason. Unfortunately we can't tell more details.

**Comment by suyogdilipkale** [comment]
@akrylysov, We are commercial product development company and want to use your desktop browser extension api for one of our product.  We are evaluating browser extensions to extend our product feature supported on **FF,Chorme, Safari, IE.** Our software product is still in conceptualization phase. We will be providing browser extension to our that will allow user to refer web sites contents and share to our application. 

We have evaluated your extension with other plugins like Crossrider, Kango etc. **Please let us know about your licensing model and charges**. Just to be your information in initial phase we won’t be charging anything to our end users.

Please reply to us as early as possible.
