### ISSUE TITLE
Kango IE11 + W8.1

### ISSUE THREAD

**Issue by pwct2p** [KangoExtensions/kango#83]
Hello,
Some users of our extension said that IE11 extension (+ W8.1) often freezes et seems deactivated even if it is installed and activated.
They need to deactivate/activate extension and restart browser to make extension active. Do you know this issue ? We use Kango 1.3.1. Is there a fix in 1.3.3 version ?
Thx

**Comment by akrylysov** [comment]
Please send your extension to extensions@kangoextensions.com.
