### ISSUE TITLE
Extension is not enabled by default in IE

### ISSUE THREAD

**Issue by matthill** [KangoExtensions/kango#84]
Running Windows 2008 R2 Standard, IE10
1. After plugin install, I restarted IE upon the notification. I couldn't find plugin icon in the plugin bar initially. This is because the plugin isn’t enabled by default.
   Suggestion: to make plugin enabled by default after restart.
2. After enabling the plugin, the icon is blank at first. It required another IE restart to see the plugin icon.

Screenshot of blank plugin icon attached.

**Comment by matthill** [comment]
![missing_plugin](https://f.cloud.github.com/assets/508260/2473617/f9359554-b042-11e3-86a2-b105438ef248.png)

**Comment by akrylysov** [comment]
Workaround sent via email.
