### ISSUE TITLE
Методы для чтения Cookies

### ISSUE THREAD

**Issue by egnevushev** [KangoExtensions/kango#86]
Добрый вечер. К сожалению, не нашел в документации информации об API для чтения хранящихся в браузере cookies. Интересно, что на гитхабе советовали использовать kango.browser.cookies для этих целей, но в документации ни слова об этом нет. Так существует ли все-таки такая возможность? Ваш фраймворк мог бы мне очень помочь, но чтение cookies - очень важная часть проекта. Заранее, большое спасибо за ответ

**Comment by akrylysov** [comment]
Поддержка кук есть, но работает она не во всех браузерах, поэтому и не документирована. Если очень хочется, то можно использовать `kango.browser.cookies`:

``` javascript
kango.browser.cookies = {
    getCookies: function(url, callback) {},

    getCookie: function(url, name, callback) {},

    setCookie: function(url, props) {}
};
```

Для этого в extension_info.json нужно добавить:

``` javascript
"permissions": {
    "cookies": true
}
```

**Comment by egnevushev** [comment]
Благодарю. А можно узнать подробнее насчет поддержки браузеров, в каких браузерах нет поддержки кук?

**Comment by akrylysov** [comment]
`kango.browser.cookies` не работает в Safari.
