### ISSUE TITLE
Kango Internet Explorer Support

### ISSUE THREAD

**Issue by causaliq** [KangoExtensions/kango#89]
We are a small non-profit organisation in London using Kango to produce an add-on which suggests volunteering opportunities to help charities across the UK. We need to support the plugin on Internet Explorer but see from other threads that an IE license is no longer offered,

Please please can you suggest a way we can get Internet Explorer support.

**Comment by akrylysov** [comment]
Sorry, we temporary don't provide commercial licenses.

**Comment by causaliq** [comment]
Hi Artem,

can you say when you might provide commercial licenses again, or provide
any other means of creating an IE extension. many thanks for your help, Ken
