### ISSUE TITLE
Ajax post method

### ISSUE THREAD

**Issue by ramiisc** [KangoExtensions/kango#9]
I want to make ajax call using post method but the problem is i am unable to set  post parameters dynamically.  Could please suggest how to do it?

**Comment by akrylysov** [comment]
Please attach code example.

**Comment by ramiisc** [comment]
here is my code:
var username = document.getElementById("username");
    var password = document.getElementById("password");
    var paramsString = "{"+"username:"+username+","+"password:"+password+"}";
    var details = {
        method: 'POST',
        url:http://localhost:9090/ReDesignPlugin/LoginController ,
        async: false,
        params: paramsString,
        headers: {'If-Modified-Since': 'Sat, 1 Jan 2000 00:00:00 GMT', 'Cache-Control': 'max-age=0'},
        contentType: 'text'
    };

```
kango.xhr.send(details, function(data) {
    if(data.status == 200 && data.response != null) {
            var text = data.response;
            console.log(text);
    }
    else { // something went wrong
            console.log('something went wrong');
    }
})
```

**Comment by ramiisc** [comment]
i am reading values like
var username = document.getElementById("username").value;
var password = document.getElementById("password").value;

**Comment by akrylysov** [comment]
What the problem? What do you mean "post parameters dynamically"?

**Comment by ramiisc** [comment]
The above code is not working. In the kango documentation, you set the ajax post method  with static parameters wwith values like  params: {'param1': '1', 'param2': '2'}, but i want to set these parameters  dynamically reading from the html form like 
var username = document.getElementById("username");
var password = document.getElementById("password");
paramsString = "{"+"username:"+username+","+"password:"+password+"}"
params: paramsString in Details object.

**Comment by akrylysov** [comment]
It's not Kango related issue. You should use document.getElementById("username").value. Please use http://stackoverflow.com/ for such questions in future.

**Comment by ramiisc** [comment]
i have committed mistake at paramsString = "{"+"username:"+username+","+"password:"+password+"}". I came to kmow that you have used key value pair object like paramsString = {"username":username, "password":password }. I pasted wrong one.

**Comment by ramiisc** [comment]
thanks for your quick support.
