### ISSUE TITLE
Extension icon not available in FF 29+

### ISSUE THREAD

**Issue by g2010a** [KangoExtensions/kango#91]
Hi,
Since the upgrade to Firefox 29+, application icons are no longer visible and also do not appear in the "customize the menu and screens" screen.

To reproduce the issue:
1. Compile a Kango Framework app that displays an icon
2. Install the app in Firefox 29+
3. Attempt to add the app icon to the menu bar

The icon is invisible although the app is running (I have verified through console logs). Everything works as expected in Chrome.

Could you please investigate why icons disappeared after FF29?

Thanks!

**Comment by akrylysov** [comment]
Please try the new version http://kangoextensions.com/kango/kango-1.3.8-public.zip

**Comment by g2010a** [comment]
It's working now, thanks!

**Comment by g2010a** [comment]
Note to anyone having this issue: I had to remove the extensions and restart firefox before re-installing it.
