### ISSUE TITLE
Not able to call popup window from created Extension

### ISSUE THREAD

**Issue by suganthiravichandran** [KangoExtensions/kango#93]
I have created the sample extension with kango. i have tried to open popup window on button click from extension. Only opening of new window and new tab is possible.

**Comment by akrylysov** [comment]
Please provide us compiled extension.

**Comment by suganthiravichandran** [comment]
I can't able to understand what you are asking. Can you please provide the steps to get compilied extension

**Comment by akrylysov** [comment]
Please send .crx or .xpi extension file.

**Comment by suganthiravichandran** [comment]
Thank you for your response. I have find the solution.BY mistake i used the wrong API function so it can't be open. Now its working properly. Once again thank You so much for your response.
