### ISSUE TITLE
Safari Options page

### ISSUE THREAD

**Issue by Rpsl** [KangoExtensions/kango#94]
Если у плагина задекларирована страница настроек, то для Safari можно делать переключатель в настройках плагина который будет её открывать.

![#](http://cl.ly/image/222f3V121r3J/ScreenShot_2014-06-04_15.53.50.png)

**Comment by akrylysov** [comment]
Хорошая идея, в новой версии будет.

**Comment by akrylysov** [comment]
Fixed in Kango 1.7.
