### ISSUE TITLE
Install into firefox 30 or 29.0.1

### ISSUE THREAD

**Issue by TheRubble** [KangoExtensions/kango#95]
Hi,

Is there anything special needed to be done to allow a plugin to install into firefox 30 or 29.01. At the moment all I get is incompatible.

Using version 1.3.8 of the framework.

Thanks

**Comment by akrylysov** [comment]
Please send us your XPI to extensions@kangoextensions.com

**Comment by TheRubble** [comment]
I've done that, also attached the chrome file incase that helps at all. The code isn't pretty or right in all places. It's the first drop from a crossrider rewrite.

Thanks

**Comment by TheRubble** [comment]
Solved the issue it was to do with auto update location not being secure.
