### ISSUE TITLE
how to communicate with content script from popup.html in kango frame work

### ISSUE THREAD

**Issue by suganthiravichandran** [KangoExtensions/kango#96]
I have tried to create cross browser extension using kango framework. I need a way to make a communication between content script and popup.html. Please help me.

**Comment by akrylysov** [comment]
You can subscribe to messages in your popup using kango.addMessageListener, then dispatch message from content script using kango.dispatchMessage. Take a look at [Messaging demo sample](https://github.com/KangoExtensions/kango-samples/tree/master/MessagingDemo/src/common).
