### ISSUE TITLE
Greasemonkey breaks extensions in Firefox

### ISSUE THREAD

**Issue by RuudBurger** [KangoExtensions/kango#97]
When I enable Greasemonkey together with a extension made in Kango, I get the following browser error inside browser console (Shift + CMD + J): 
`Error during async call method kango.userscript.getScripts. Details: TypeError: b is undefined`
The button shows, but nothing else. If I disable Greasemonkey again, everything works like it should.

BTW this only fails after you've restarted Firefox so somewhere Greasemonkey must be overwriting some functions of Kango.
Tried to trace it down, but the minified code with variable names a,b,c,d doesn't make it easier.

Hope you guys can help me out.

**Comment by akrylysov** [comment]
Please try the new version http://kangoextensions.com/kango/kango-1.3.8-public.zip
