### ISSUE TITLE
Problem with KangoEngine.exe and Avast

### ISSUE THREAD

**Issue by AnatoleH** [KangoExtensions/kango#98]
HI

I recently got a problem  with my extension made with Kango, Avast blocks the download cause of KangoEngine.exe, is there any way you can fix it ?

**Comment by akrylysov** [comment]
Please send compiled extension to extensions@kangoextensions.com

**Comment by AnatoleH** [comment]
I've sent it Friday did you get it ?

**Comment by akrylysov** [comment]
Unfortunately no, please try to use password-protected zip.

**Comment by sebastienwerle** [comment]
Hi,

I also have the same problem with my extension made with Kango.
@akrylysov : Do you have a solution to fix this embarrassing problem?

Thank you for your feedback
Regards

**Comment by akrylysov** [comment]
Please send compiled extension to extensions@kangoextensions.com

**Comment by sebastienwerle** [comment]
Hi

I've just send it. Our customer represents a big bank in France and we have to fix this very quickly.
It would be great if you have time to check this trouble

Thanks a lot
