### ISSUE TITLE
License renewal

### ISSUE THREAD

**Issue by pwct2p** [KangoExtensions/kango#99]
Hello,

We want to extend our license and we didn't get any response. How could we contact you ?

Thank you,

**Comment by kangowhereareyou** [comment]
Hi,

I've sent countless emails and have tried contacting by skype regarding license renewals however there has been no progress made. What is going on with IE support? Is it being discontinued? Let us know something so we can plan accordingly.

**Comment by akrylysov** [comment]
Sorry, we temporarily don't provide/renew commercial support.

**Comment by akrylysov** [comment]
Sorry for inconvenience, we provide commercial support again.

**Comment by BhuvaneshMCA** [comment]
So, can i use your framework freely for chrome and Firefox?
